name: CI Code Checks

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        laravel-versions: ['5.5', '6.*', '7.*', '8.*', '9.*', '10.*', '11.*']
        exclude:
          - php-versions: '7.4'
            laravel-versions: '9.*'
          - php-versions: '7.4'
            laravel-versions: '10.*'
          - php-versions: '7.4'
            laravel-versions: '11.*'
          - php-versions: '8.0'
            laravel-versions: '10.*'
          - php-versions: '8.0'
            laravel-versions: '11.*'
          - php-versions: '8.1'
            laravel-versions: '11.*'
    env:
      PHP_VERSION: ${{ matrix.php-versions }}
      LARAVEL_VERSION: ${{ matrix.laravel-versions }}
    name: PHP ${{ matrix.php-versions }} - Laravel ${{ matrix.laravel-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer packages
        run: composer install --prefer-dist --no-interaction

      - name: Tests Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: PHP_VERSION
          fail_ci_if_error: true
